# Generated by Django 3.2.6 on 2021-08-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mug',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
    ]
