# Generated by Django 3.2.6 on 2021-08-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_mug_in_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mug',
            name='in_use',
        ),
    ]
