# Generated by Django 3.2.6 on 2021-08-17 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_mug_in_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'Coffee'), ('T', 'Tea'), ('S', 'Soup'), ('O', 'Other')], default='C', max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('mug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mug')),
            ],
        ),
    ]
