# Generated by Django 3.2.6 on 2021-08-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_mug_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mug',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
