# Generated by Django 3.2.6 on 2021-08-18 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_mug_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='mug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.mug'),
        ),
    ]
