# Generated by Django 3.2.6 on 2021-08-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_drink_mug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mug',
            name='coasters',
            field=models.ManyToManyField(to='main_app.Coaster'),
        ),
    ]
